//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entty_Framework_Model_First.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class box
    {
        public int Id { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
    }
}
